---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  become: yes
  remote_user: vagrant

  
  tasks:
    - name: Install required packages
      apt: 
          name: "{{ packages }}"
      vars:
          packages:
              - language-pack-ru  
              - ntp
              - ntpdate 

    - name: Creater user ceph_admin
      user:
          name: ceph_admin
          groups: sudo

    - name: Set authorized key took from file
      authorized_key:
          user: ceph_admin
          state: present
          key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"

    - name: Copy file ceph_admin for run commands wothout password 
      copy:
        src: files/ceph_admin.sudors
        dest: /etc/sudoers.d/ceph_admin
        mode: 0440


